### ISSUE TITLE
フィード生成に失敗する Maximum call stack size exceeded

### ISSUE THREAD

**Issue by azu** [jser/watch-list-rss#1]
https://github.com/jser/watch-list-rss/blob/6e15a0232d2c7d9398c7a1e68affa4ffe3c1aa95/src/site/blog-feed.njk#L32

ここをレンダリングするときに、特定の値でMaximum call stack size exceededのエラーが発生する

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./src/site/blog-feed.njk (via TemplateContentRenderError)
[11ty] 2. (./src/site/blog-feed.njk)
[11ty]   EleventyShortcodeError: Error with Nunjucks shortcode `image` (via Template render error)
[11ty] 3. Maximum call stack size exceeded (via Template render error)
[11ty] 
[11ty] Original error stack trace: RangeError: Maximum call stack size exceeded
[11ty]     at Reflect.getOwnPropertyDescriptor (<anonymous>)
[11ty]     at Object.getOwnPropertyDescriptor (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/@11ty/eleventy/src/Util/ProxyWrap.js:9:24)
[11ty]     at Reflect.getOwnPropertyDescriptor (<anonymous>)
[11ty]     at Object.getOwnPropertyDescriptor (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/@11ty/eleventy/src/Util/ProxyWrap.js:9:24)
[11ty]     at Object.memberLookup (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/runtime.js:201:17)
[11ty]     at eval (eval at _compile (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:62:84)
[11ty]     at eval (eval at _compile (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:66:3)
[11ty]     at iterCallback (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/runtime.js:236:11)
[11ty]     at next (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/lib.js:258:7)
[11ty]     at eval (eval at _compile (/home/runner/work/watch-list-rss/watch-list-rss/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:94:1)
[11ty] Benchmark    469ms  13%     1× (Data) `./src/site/_data/blogFeeds.js`
[11ty] Copied 17 files / Wrote 0 files in 3.28 seconds (v2.0.1)
Error: Process completed with exit code 1.
```

https://github.com/jser/watch-list-rss/actions/runs/7859288448

**Comment by azu** [comment]
問題が起きるフィード

- https://www.aha.io/blog
